services:
  papercut:
    image: changemakerstudiosus/papercut-smtp:7.0.0-rc1
    container_name: jala-papercut
    ports:
      - '8080:80'
      - '25:25'

  redis:
    image: redislabs/redismod
    container_name: jala-redis
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

  postgres:
    image: postgres:17
    container_name: jala-postgres
    environment:
      - POSTGRES_DB=postgres-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

    ai-service:
      build: ./services/ai-team-generator
      container_name: jala-ai-service
      environment:
        - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      ports:
        - '8001:8001'
    depends_on:
      - redis

volumes:
  redis-data:
  postgres-data:
